version: "2"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
    - "3000:3000"
    links:
    - mongo
    environment:
    - NODE_ENV=production
  mongo:
    container_name: mongo-app
    image: mongo
    volumes:
    - ./data:/data/db
    ports:
    - "27017:27017"